# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 20f764720e82f5f2e6b8203b7823d06e50e3ee3b266c614fe3cc05434cabfcec69e64814912adb486aa3f3343a51bdee7e00030d6c2df40098f34840bc8c076d

test:
  secret_key_base: 809e9095564ef54a1ee49fde8a1d9087ffaa27c7c4fdfbd023feb83a33c0eb02815560207afa417ec6287854a8f174eb1bfa1059f5f9e106f10b730ddf879da6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
